Repository Trinity-goorm/TRI-BE, pull requests merged in 2025-02, with the labels that each got.

#11 Tri 48 available seats api 구현 및 스웨거 등 설정
  build.gradle
  src/main/java/com/trinity/ctc/config/SecurityConfig.java
  src/main/java/com/trinity/ctc/config/SwaggerConfig.java
  src/main/java/com/trinity/ctc/domain/reservation/controller/ReservationController.java
  src/main/java/com/trinity/ctc/domain/reservation/entity/Reservation.java
  src/main/java/com/trinity/ctc/domain/reservation/entity/ReservationTime.java
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationService.java
  src/main/java/com/trinity/ctc/domain/restaurant/entity/Restaurant.java
  src/main/java/com/trinity/ctc/domain/seat/controller/SeatAvailabilityController.java
  src/main/java/com/trinity/ctc/domain/seat/dto/GroupedDailyAvailabilityResponse.java
  src/main/java/com/trinity/ctc/domain/seat/dto/GroupedSeatResponse.java
  src/main/java/com/trinity/ctc/domain/seat/dto/GroupedTimeSlotResponse.java
  src/main/java/com/trinity/ctc/domain/seat/entity/SeatAvailability.java
  src/main/java/com/trinity/ctc/domain/seat/entity/SeatType.java
  src/main/java/com/trinity/ctc/domain/seat/repository/SeatAvailabilityRepository.java
  src/main/java/com/trinity/ctc/domain/seat/service/SeatAvailabilityService.java
  src/main/java/com/trinity/ctc/util/exception/error_code/DateTimeErrorCode.java
  src/main/java/com/trinity/ctc/util/exception/error_code/SeatErrorCode.java
  src/main/java/com/trinity/ctc/util/formatter/DateTimeUtil.java
  src/main/java/com/trinity/ctc/util/helper/GroupingHelper.java
  src/main/java/com/trinity/ctc/util/validator/CapacityValidator.java
  src/main/java/com/trinity/ctc/util/validator/DateTimeValidator.java
  src/main/java/com/trinity/ctc/util/validator/SeatAvailabilityValidator.java
  src/main/resources/application.yml
Labels: feat

#14 Tri 50 FCM token 저장 & 삭제 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/trinity/ctc/config/FirebaseInitializer.java
  src/main/java/com/trinity/ctc/config/SwaggerConfig.java
  src/main/java/com/trinity/ctc/domain/fcm/controller/FcmController.java
  src/main/java/com/trinity/ctc/domain/fcm/dto/FcmTokenRequest.java
  src/main/java/com/trinity/ctc/domain/fcm/entity/Fcm.java
  src/main/java/com/trinity/ctc/domain/fcm/repository/FcmRepository.java
  src/main/java/com/trinity/ctc/domain/fcm/service/FcmService.java
  src/main/java/com/trinity/ctc/domain/notification/entity/NotificationHistory.java
  src/main/java/com/trinity/ctc/domain/notification/entity/ReservationNotification.java
  src/main/java/com/trinity/ctc/domain/notification/entity/SeatNotification.java
  src/main/java/com/trinity/ctc/domain/notification/entity/SeatNotificationMessage.java
  src/main/java/com/trinity/ctc/domain/notification/entity/errorCode/FcmErrorCode.java
  src/main/java/com/trinity/ctc/domain/notification/entity/type/NotificationType.java
  src/main/java/com/trinity/ctc/domain/user/entity/User.java
  src/main/java/com/trinity/ctc/kakao/controller/AuthController.java
  src/main/java/com/trinity/ctc/util/exception/error_code/FcmTokenErrorCode.java
  src/main/java/com/trinity/ctc/util/exception/error_code/FirebaseErrorCode.java
  src/main/java/com/trinity/ctc/util/formatter/DateTimeUtil.java
  src/main/resources/application.yml
Labels: feat

#15 Tri 60 preoccupy
  src/main/java/com/trinity/ctc/config/SwaggerConfig.java
  src/main/java/com/trinity/ctc/domain/reservation/controller/ReservationController.java
  src/main/java/com/trinity/ctc/domain/reservation/dto/PreoccupyResponse.java
  src/main/java/com/trinity/ctc/domain/reservation/dto/ReservationRequest.java
  src/main/java/com/trinity/ctc/domain/reservation/entity/Reservation.java
  src/main/java/com/trinity/ctc/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/trinity/ctc/domain/reservation/repository/ReservationTimeRepository.java
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationService.java
  src/main/java/com/trinity/ctc/domain/restaurant/entity/repository/RestaurantRepository.java
  src/main/java/com/trinity/ctc/domain/seat/entity/SeatAvailability.java
  src/main/java/com/trinity/ctc/domain/seat/repository/SeatAvailabilityRepository.java
  src/main/java/com/trinity/ctc/domain/seat/repository/SeatTypeRepository.java
  src/main/java/com/trinity/ctc/domain/user/entity/User.java
  src/main/java/com/trinity/ctc/util/exception/error_code/ReservationTimeErrorCode.java
  src/main/java/com/trinity/ctc/util/exception/error_code/RestaurantErrorCode.java
  src/main/java/com/trinity/ctc/util/exception/error_code/SeatErrorCode.java
  src/main/java/com/trinity/ctc/util/exception/error_code/SeatTypeErrorCode.java
  src/main/java/com/trinity/ctc/util/validator/CapacityValidator.java
  src/main/java/com/trinity/ctc/util/validator/SeatAvailabilityValidator.java
Labels: feat

#17 Tri 68 complete reservation
  src/main/java/com/trinity/ctc/domain/reservation/controller/ReservationController.java
  src/main/java/com/trinity/ctc/domain/reservation/dto/PreoccupyResponse.java
  src/main/java/com/trinity/ctc/domain/reservation/dto/ReservationRequest.java
  src/main/java/com/trinity/ctc/domain/reservation/dto/ReservationResultResponse.java
  src/main/java/com/trinity/ctc/domain/reservation/entity/Reservation.java
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationService.java
  src/main/java/com/trinity/ctc/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/trinity/ctc/util/exception/error_code/ReservationErrorCode.java
  src/main/java/com/trinity/ctc/util/validator/ReservationValidator.java
Labels: feat

#19 Tri 70 cancel preoccupied reservation
  src/main/java/com/trinity/ctc/domain/reservation/controller/ReservationController.java
  src/main/java/com/trinity/ctc/domain/reservation/entity/Reservation.java
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationService.java
  src/main/java/com/trinity/ctc/domain/seat/entity/SeatAvailability.java
Labels: feat

#21 Tri 71 cancel completed reservation
  src/main/java/com/trinity/ctc/domain/reservation/controller/ReservationController.java
  src/main/java/com/trinity/ctc/domain/reservation/dto/ReservationResultResponse.java
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationService.java
  src/main/java/com/trinity/ctc/domain/user/entity/User.java
  src/main/java/com/trinity/ctc/util/exception/error_code/ReservationErrorCode.java
  src/main/java/com/trinity/ctc/util/exception/error_code/TicketErrorCode.java
  src/main/java/com/trinity/ctc/util/validator/DateTimeValidator.java
  src/main/java/com/trinity/ctc/util/validator/ReservationValidator.java
  src/main/java/com/trinity/ctc/util/validator/TicketValidator.java
Labels: feat

#24 Tri 52 reservation notification
  src/main/java/com/trinity/ctc/CtcApplication.java
  src/main/java/com/trinity/ctc/config/FirebaseInitializer.java
  src/main/java/com/trinity/ctc/config/TreadPoolConfig.java
  src/main/java/com/trinity/ctc/domain/fcm/repository/FcmRepository.java
  src/main/java/com/trinity/ctc/domain/fcm/service/FcmService.java
  src/main/java/com/trinity/ctc/domain/notification/controller/NotificationController.java
  src/main/java/com/trinity/ctc/domain/notification/dto/FcmSendingResultDto.java
  src/main/java/com/trinity/ctc/domain/notification/entity/NotificationHistory.java
  src/main/java/com/trinity/ctc/domain/notification/entity/ReservationNotification.java
  src/main/java/com/trinity/ctc/domain/notification/entity/SeatNotificationMessage.java
  src/main/java/com/trinity/ctc/domain/notification/entity/errorCode/FcmErrorCode.java
  src/main/java/com/trinity/ctc/domain/notification/entity/result/SentResult.java
  src/main/java/com/trinity/ctc/domain/notification/entity/type/NotificationType.java
  src/main/java/com/trinity/ctc/domain/notification/repository/NotificationHistoryRepository.java
  src/main/java/com/trinity/ctc/domain/notification/repository/ReservationNotificationRepository.java
  src/main/java/com/trinity/ctc/domain/notification/repository/SeatNotificationMessageRepository.java
  src/main/java/com/trinity/ctc/domain/notification/repository/SeatNotificationRepository.java
  src/main/java/com/trinity/ctc/domain/notification/service/NotificationService.java
  src/main/java/com/trinity/ctc/domain/notification/util/NotificationMessageUtil.java
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationService.java
  src/main/java/com/trinity/ctc/domain/restaurant/entity/Restaurant.java
  src/main/java/com/trinity/ctc/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/trinity/ctc/domain/seat/service/SeatAvailabilityService.java
  src/main/java/com/trinity/ctc/event/PreOccupancyCanceledEvent.java
  src/main/java/com/trinity/ctc/event/ReservationCanceledEvent.java
  src/main/java/com/trinity/ctc/event/ReservationCompleteEvent.java
  src/main/java/com/trinity/ctc/kakao/repository/UserRepository.java
  src/main/java/com/trinity/ctc/listener/ReservationEventListener.java
  src/main/java/com/trinity/ctc/util/exception/error_code/FcmErrorCode.java
  src/main/java/com/trinity/ctc/util/exception/error_code/JsonParseErrorCode.java
  src/main/java/com/trinity/ctc/util/formatter/JsonConverter.java
Labels: feat

#27 Tri 76 preoccupy v2
  src/main/java/com/trinity/ctc/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationService.java
  src/main/java/com/trinity/ctc/domain/reservation/validator/ReservationValidator.java
  src/main/java/com/trinity/ctc/domain/restaurant/entity/Restaurant.java
  src/main/java/com/trinity/ctc/domain/seat/entity/SeatType.java
  src/main/java/com/trinity/ctc/domain/user/entity/User.java
  src/main/java/com/trinity/ctc/util/exception/error_code/ReservationErrorCode.java
  src/main/java/com/trinity/ctc/util/validator/ReservationValidator.java
Labels: fix

#31 Tri 79 seat notification api
  src/main/java/com/trinity/ctc/config/SwaggerConfig.java
  src/main/java/com/trinity/ctc/domain/fcm/controller/FcmController.java
  src/main/java/com/trinity/ctc/domain/notification/controller/NotificationController.java
  src/main/java/com/trinity/ctc/domain/notification/dto/FcmSendingResultDto.java
  src/main/java/com/trinity/ctc/domain/notification/dto/SubscriptionListResponse.java
  src/main/java/com/trinity/ctc/domain/notification/dto/SubscriptionResponse.java
  src/main/java/com/trinity/ctc/domain/notification/entity/NotificationHistory.java
  src/main/java/com/trinity/ctc/domain/notification/entity/ReservationNotification.java
  src/main/java/com/trinity/ctc/domain/notification/entity/SeatNotification.java
  src/main/java/com/trinity/ctc/domain/notification/entity/SeatNotificationMessage.java
  src/main/java/com/trinity/ctc/domain/notification/entity/result/SentResult.java
  src/main/java/com/trinity/ctc/domain/notification/repository/ReservationNotificationRepository.java
  src/main/java/com/trinity/ctc/domain/notification/repository/SeatNotificationMessageRepository.java
  src/main/java/com/trinity/ctc/domain/notification/repository/SeatNotificationRepository.java
  src/main/java/com/trinity/ctc/domain/notification/result/SentResult.java
  src/main/java/com/trinity/ctc/domain/notification/service/NotificationService.java
  src/main/java/com/trinity/ctc/domain/notification/type/NotificationType.java
  src/main/java/com/trinity/ctc/domain/notification/util/fomatter/NotificationMessageUtil.java
  src/main/java/com/trinity/ctc/domain/user/entity/User.java
  src/main/java/com/trinity/ctc/event/ReservationCanceledEvent.java
  src/main/java/com/trinity/ctc/event/SeatNotificationSubscribedEvent.java
  src/main/java/com/trinity/ctc/util/exception/error_code/EmptyTicketErrorCode.java
  src/main/java/com/trinity/ctc/util/exception/error_code/NotificationErrorCode.java
  src/main/java/com/trinity/ctc/util/exception/error_code/SeatErrorCode.java
  src/main/java/com/trinity/ctc/util/formatter/JsonUtil.java
  src/main/java/com/trinity/ctc/util/validator/TicketValidator.java
Labels: feat

#36 Tri 85 available reservation data
  dummy.ddl
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationTimeService.java
  src/main/java/com/trinity/ctc/domain/restaurant/service/RestaurantService.java
  src/main/java/com/trinity/ctc/domain/seat/entity/SeatAvailability.java
  src/main/java/com/trinity/ctc/domain/seat/mode/DateRangeMode.java
  src/main/java/com/trinity/ctc/domain/seat/repository/SeatAvailabilityRepository.java
  src/main/java/com/trinity/ctc/domain/seat/scheduler/SeatAvailabilityScheduler.java
  src/main/java/com/trinity/ctc/domain/seat/service/SeatAvailabilityBatchService.java
  src/main/java/com/trinity/ctc/domain/seat/service/SeatAvailabilityService.java
  src/main/java/com/trinity/ctc/domain/seat/service/SeatTypeService.java
  src/main/java/com/trinity/ctc/util/exception/error_code/SeatErrorCode.java
  src/main/java/com/trinity/ctc/util/validator/DateTimeValidator.java
  src/main/java/com/trinity/ctc/util/validator/SeatAvailabilityValidator.java
  src/main/resources/application-local.yml
Labels: feat

#39 Tri 100 preoccupy v3
  src/main/java/com/trinity/ctc/domain/seat/dto/GroupedSeatResponse.java
Labels: fix

#43 TRI 103 onboarding save api
  dummy.ddl
  src/main/java/com/trinity/ctc/config/SwaggerConfig.java
  src/main/java/com/trinity/ctc/domain/fcm/service/FcmService.java
  src/main/java/com/trinity/ctc/domain/like/service/LikeService.java
  src/main/java/com/trinity/ctc/domain/notification/controller/NotificationController.java
  src/main/java/com/trinity/ctc/domain/notification/dto/SubscriptionResponse.java
  src/main/java/com/trinity/ctc/domain/notification/entity/SeatNotification.java
  src/main/java/com/trinity/ctc/domain/notification/service/NotificationService.java
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationService.java
  src/main/java/com/trinity/ctc/domain/restaurant/service/RestaurantRecommendationService.java
  src/main/java/com/trinity/ctc/domain/restaurant/service/RestaurantService.java
  src/main/java/com/trinity/ctc/domain/search/service/SearchService.java
  src/main/java/com/trinity/ctc/domain/seat/controller/SeatAvailabilityController.java
  src/main/java/com/trinity/ctc/domain/user/controller/UserController.java
  src/main/java/com/trinity/ctc/domain/user/dto/OnboardingRequest.java
  src/main/java/com/trinity/ctc/domain/user/entity/User.java
  src/main/java/com/trinity/ctc/domain/user/entity/UserPreference.java
  src/main/java/com/trinity/ctc/domain/user/entity/UserPreferenceCategory.java
  src/main/java/com/trinity/ctc/domain/user/entity/compositeKey/UserPreferenceCategoryKey.java
  src/main/java/com/trinity/ctc/domain/user/repository/UserPreferenceCategoryRepository.java
  src/main/java/com/trinity/ctc/domain/user/repository/UserPreferenceRepository.java
  src/main/java/com/trinity/ctc/domain/user/repository/UserRepository.java
  src/main/java/com/trinity/ctc/domain/user/service/UserService.java
  src/main/java/com/trinity/ctc/kakao/controller/AuthController.java
  src/main/java/com/trinity/ctc/kakao/service/AuthService.java
  src/main/java/com/trinity/ctc/util/exception/error_code/UserErrorCode.java
  src/test/java/com/trinity/ctc/kakao/repository/UserRepositoryTest.java
Labels: feat

#44 Tri 104 seat data v2
  .gitignore
  build.gradle
  src/main/java/com/trinity/ctc/domain/seat/mode/DateRangeMode.java
  src/main/java/com/trinity/ctc/domain/seat/scheduler/SeatAvailabilityScheduler.java
  src/main/java/com/trinity/ctc/domain/seat/service/SeatAvailabilityBatchService.java
  src/main/java/com/trinity/ctc/loader/DataLoader.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: feat, fix

#46 TRI-107 사용자 정보 반환 로직 구현
  src/main/java/com/trinity/ctc/domain/user/controller/UserController.java
  src/main/java/com/trinity/ctc/domain/user/dto/UserDetailResponse.java
  src/main/java/com/trinity/ctc/domain/user/service/UserService.java
Labels: feat

#51 Tri 108 cancel reservation v2
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationService.java
  src/main/java/com/trinity/ctc/domain/reservation/validator/ReservationValidator.java
  src/main/java/com/trinity/ctc/util/exception/error_code/ReservationErrorCode.java
  src/main/java/com/trinity/ctc/util/validator/DateTimeValidator.java
  src/test/java/com/trinity/ctc/util/DateTimeUtilTest.java
Labels: fix

#53 Tri 111 empty ticket init
  dummy.ddl
  src/main/java/com/trinity/ctc/domain/notification/scheduler/NotificationScheduler.java
  src/main/java/com/trinity/ctc/domain/notification/service/NotificationService.java
  src/main/java/com/trinity/ctc/domain/user/entity/User.java
  src/main/java/com/trinity/ctc/domain/user/repository/UserPreferenceRepository.java
  src/main/java/com/trinity/ctc/domain/user/scheduler/UserScheduler.java
  src/main/java/com/trinity/ctc/domain/user/service/UserService.java
Labels: feat

#54 Tri 114 my reservation list
  src/main/java/com/trinity/ctc/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/trinity/ctc/domain/restaurant/entity/Restaurant.java
  src/main/java/com/trinity/ctc/domain/restaurant/entity/RestaurantCategory.java
  src/main/java/com/trinity/ctc/domain/seat/dto/SeatTypeInfoResponse.java
  src/main/java/com/trinity/ctc/domain/user/controller/UserController.java
  src/main/java/com/trinity/ctc/domain/user/dto/UserReservationListResponse.java
  src/main/java/com/trinity/ctc/domain/user/dto/UserReservationResponse.java
  src/main/java/com/trinity/ctc/domain/user/service/UserService.java
  src/main/java/com/trinity/ctc/util/common/SortOrder.java
  src/main/java/com/trinity/ctc/util/validator/DateTimeValidator.java
Labels: feat

#58 Tri 116 reservation process notification
  src/main/java/com/trinity/ctc/domain/fcm/entity/Fcm.java
  src/main/java/com/trinity/ctc/domain/notification/dto/FcmMessageDto.java
  src/main/java/com/trinity/ctc/domain/notification/service/NotificationService.java
  src/main/java/com/trinity/ctc/domain/notification/type/NotificationType.java
  src/main/java/com/trinity/ctc/domain/notification/util/fomatter/NotificationMessageUtil.java
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationService.java
  src/main/java/com/trinity/ctc/event/PreOccupancyCanceledEvent.java
  src/main/java/com/trinity/ctc/event/ReservationCanceledEvent.java
  src/main/java/com/trinity/ctc/event/ReservationCompleteEvent.java
  src/main/java/com/trinity/ctc/event/SeatNotificationSubscribedEvent.java
  src/main/java/com/trinity/ctc/listener/ReservationEventListener.java
Labels: feat

#60 Tri 117 fix notification history
  src/main/java/com/trinity/ctc/domain/fcm/repository/FcmRepository.java
  src/main/java/com/trinity/ctc/domain/notification/controller/NotificationController.java
  src/main/java/com/trinity/ctc/domain/notification/dto/FcmMessageDto.java
  src/main/java/com/trinity/ctc/domain/notification/dto/GroupFcmInformationDto.java
  src/main/java/com/trinity/ctc/domain/notification/entity/NotificationHistory.java
  src/main/java/com/trinity/ctc/domain/notification/service/NotificationService.java
  src/main/java/com/trinity/ctc/domain/user/controller/UserController.java
  src/main/java/com/trinity/ctc/domain/user/service/UserService.java
  src/main/java/com/trinity/ctc/domain/user/validator/UserValidator.java
  src/main/java/com/trinity/ctc/util/formatter/PhonNumberUtil.java
Labels: fix

#62 Tri 120 seat entity refactoring
  src/main/java/com/trinity/ctc/config/SwaggerConfig.java
  src/main/java/com/trinity/ctc/domain/notification/dto/SubscriptionResponse.java
  src/main/java/com/trinity/ctc/domain/notification/entity/SeatNotificationMessage.java
  src/main/java/com/trinity/ctc/domain/notification/repository/SeatNotificationMessageRepository.java
  src/main/java/com/trinity/ctc/domain/notification/repository/SeatNotificationRepository.java
  src/main/java/com/trinity/ctc/domain/notification/service/NotificationService.java
  src/main/java/com/trinity/ctc/domain/reservation/entity/ReservationTime.java
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationService.java
  src/main/java/com/trinity/ctc/domain/restaurant/entity/Restaurant.java
  src/main/java/com/trinity/ctc/domain/restaurant/service/RestaurantService.java
  src/main/java/com/trinity/ctc/domain/seat/controller/SeatController.java
  src/main/java/com/trinity/ctc/domain/seat/dto/GroupedSeatResponse.java
  src/main/java/com/trinity/ctc/domain/seat/entity/Seat.java
  src/main/java/com/trinity/ctc/domain/seat/entity/SeatType.java
  src/main/java/com/trinity/ctc/domain/seat/repository/SeatAvailabilityRepository.java
  src/main/java/com/trinity/ctc/domain/seat/repository/SeatRepository.java
  src/main/java/com/trinity/ctc/domain/seat/scheduler/SeatAvailabilityScheduler.java
  src/main/java/com/trinity/ctc/domain/seat/scheduler/SeatScheduler.java
  src/main/java/com/trinity/ctc/domain/seat/service/SeatBatchService.java
  src/main/java/com/trinity/ctc/domain/seat/service/SeatService.java
  src/main/java/com/trinity/ctc/event/PreOccupancyCanceledEvent.java
  src/main/java/com/trinity/ctc/event/ReservationCanceledEvent.java
  src/main/java/com/trinity/ctc/listener/ReservationEventListener.java
  src/main/java/com/trinity/ctc/loader/DataLoader.java
  src/main/java/com/trinity/ctc/util/exception/error_code/RestaurantErrorCode.java
  src/main/java/com/trinity/ctc/util/formatter/PhoneNumberUtil.java
  src/main/java/com/trinity/ctc/util/helper/GroupingHelper.java
  src/main/java/com/trinity/ctc/util/validator/SeatAvailabilityValidator.java
Labels: refactor

#68 TRI-127 사용자 정보반환 시, 전화번호 추가 반환
  src/main/java/com/trinity/ctc/domain/user/dto/UserDetailResponse.java
  src/main/java/com/trinity/ctc/domain/user/service/UserService.java
Labels: feat

#70 Tri 131 setting v1
  docker-compose.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: CI/CD

#72 Fix - 가용 자리 개수가 0미만인지 확인하는 validator 추가
  src/main/java/com/trinity/ctc/domain/seat/entity/Seat.java
  src/main/java/com/trinity/ctc/util/validator/CapacityValidator.java
Labels: fix

#75 Tri 134 fix noti dto
  src/main/java/com/trinity/ctc/domain/fcm/controller/FcmController.java
  src/main/java/com/trinity/ctc/domain/fcm/dto/FcmTokenRequest.java
  src/main/java/com/trinity/ctc/domain/fcm/service/FcmService.java
  src/main/java/com/trinity/ctc/domain/notification/service/NotificationService.java
  src/main/java/com/trinity/ctc/kakao/controller/AuthController.java
  src/main/java/com/trinity/ctc/kakao/service/KakaoApiService.java
Labels: fix

#81 Tri 137 onboarding nickname
  src/main/java/com/trinity/ctc/domain/user/dto/OnboardingRequest.java
  src/main/java/com/trinity/ctc/domain/user/entity/User.java
Labels: feat, fix

#85 Tri 139 set notification module
  src/main/java/com/trinity/ctc/domain/notification/service/NotificationService.java
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationService.java
  src/main/java/com/trinity/ctc/event/PreOccupancyCanceledEvent.java
  src/main/java/com/trinity/ctc/event/ReservationCanceledEvent.java
  src/main/java/com/trinity/ctc/event/ReservationCompleteEvent.java
  src/main/java/com/trinity/ctc/listener/ReservationEventListener.java
Labels: fix

#86 Tri 141 data insert
  src/main/java/com/trinity/ctc/config/SwaggerConfig.java
  src/main/java/com/trinity/ctc/domain/reservation/dto/InsertReservationTimeRequest.java
  src/main/java/com/trinity/ctc/domain/reservation/entity/ReservationTime.java
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationTimeService.java
  src/main/java/com/trinity/ctc/domain/seat/dto/InsertSeatTypeRequest.java
  src/main/java/com/trinity/ctc/domain/seat/entity/SeatType.java
  src/main/java/com/trinity/ctc/domain/seat/service/SeatTypeService.java
  src/main/java/com/trinity/ctc/loader/DataLoader.java
  src/main/java/com/trinity/ctc/loader/controller/DataController.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: feat

#87 TRI-139 온보딩 requestDTO attribute 이름 변경
  src/main/java/com/trinity/ctc/domain/user/dto/OnboardingRequest.java
  src/main/java/com/trinity/ctc/domain/user/entity/User.java
Labels: fix

#88 TRI-139 온보딩 requestDTO 순서변경
  src/main/java/com/trinity/ctc/domain/user/dto/OnboardingRequest.java
Labels: fix

#90 Tri 139 set notification module
  src/main/java/com/trinity/ctc/domain/notification/controller/NotificationController.java
  src/main/java/com/trinity/ctc/domain/notification/service/NotificationService.java
  src/main/java/com/trinity/ctc/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/trinity/ctc/domain/user/service/UserService.java
  src/main/java/com/trinity/ctc/domain/user/validator/UserValidator.java
  src/main/java/com/trinity/ctc/event/ReservationCanceledEvent.java
  src/main/java/com/trinity/ctc/listener/ReservationEventListener.java
  src/main/java/com/trinity/ctc/util/exception/error_code/FcmErrorCode.java
  src/main/java/com/trinity/ctc/util/exception/error_code/NotificationErrorCode.java
  src/main/java/com/trinity/ctc/util/exception/error_code/UserErrorCode.java
Labels: fix

#89 [TRI-150] 배포 25.02.25 16:43
  build.gradle
  src/main/java/com/trinity/ctc/config/SecurityConfig.java
  src/main/java/com/trinity/ctc/config/SwaggerConfig.java
  src/main/java/com/trinity/ctc/domain/ai/AIRecommendationClient.java
  src/main/java/com/trinity/ctc/domain/ai/dto/AIRecommendationRequest.java
  src/main/java/com/trinity/ctc/domain/fcm/controller/FcmController.java
  src/main/java/com/trinity/ctc/domain/fcm/dto/FcmTokenRequest.java
  src/main/java/com/trinity/ctc/domain/fcm/service/FcmService.java
  src/main/java/com/trinity/ctc/domain/notification/controller/NotificationController.java
  src/main/java/com/trinity/ctc/domain/notification/service/NotificationService.java
  src/main/java/com/trinity/ctc/domain/notification/util/fomatter/NotificationMessageUtil.java
  src/main/java/com/trinity/ctc/domain/reservation/dto/InsertReservationTimeRequest.java
  src/main/java/com/trinity/ctc/domain/reservation/entity/ReservationTime.java
  src/main/java/com/trinity/ctc/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationService.java
  src/main/java/com/trinity/ctc/domain/reservation/service/ReservationTimeService.java
  src/main/java/com/trinity/ctc/domain/restaurant/service/RestaurantFileLoader.java
  src/main/java/com/trinity/ctc/domain/restaurant/service/RestaurantRecommendationService.java
  src/main/java/com/trinity/ctc/domain/seat/dto/InsertSeatTypeRequest.java
  src/main/java/com/trinity/ctc/domain/seat/entity/SeatType.java
  src/main/java/com/trinity/ctc/domain/seat/service/SeatTypeService.java
  src/main/java/com/trinity/ctc/domain/user/dto/OnboardingRequest.java
  src/main/java/com/trinity/ctc/domain/user/entity/User.java
  src/main/java/com/trinity/ctc/domain/user/service/UserService.java
  src/main/java/com/trinity/ctc/domain/user/validator/UserValidator.java
  src/main/java/com/trinity/ctc/event/PreOccupancyCanceledEvent.java
  src/main/java/com/trinity/ctc/event/ReservationCanceledEvent.java
  src/main/java/com/trinity/ctc/event/ReservationCompleteEvent.java
  src/main/java/com/trinity/ctc/kakao/config/KakaoApiProperties.java
  src/main/java/com/trinity/ctc/kakao/controller/AuthController.java
  src/main/java/com/trinity/ctc/kakao/dto/KakaoLogoutResponse.java
  src/main/java/com/trinity/ctc/kakao/dto/UserLoginResponse.java
  src/main/java/com/trinity/ctc/kakao/service/AuthService.java
  src/main/java/com/trinity/ctc/kakao/service/KakaoApiService.java
  src/main/java/com/trinity/ctc/listener/ReservationEventListener.java
  src/main/java/com/trinity/ctc/loader/DataLoader.java
  src/main/java/com/trinity/ctc/loader/controller/DataController.java
  src/main/java/com/trinity/ctc/util/exception/error_code/FcmErrorCode.java
  src/main/java/com/trinity/ctc/util/exception/error_code/KakaoErrorCode.java
  src/main/java/com/trinity/ctc/util/exception/error_code/NotificationErrorCode.java
  src/main/java/com/trinity/ctc/util/exception/error_code/UserErrorCode.java
  src/main/java/com/trinity/ctc/util/formatter/PhoneNumberUtil.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: release

#92 [TRI-152] 배포 25.02.25 20:46
  src/main/java/com/trinity/ctc/domain/category/service/CategoryFileLoader.java
  src/main/java/com/trinity/ctc/domain/restaurant/service/RestaurantFileLoader.java
Labels: release

#94 [TRI-153] 배포 25.02.26 11:29
  src/main/java/com/trinity/ctc/domain/fcm/controller/FcmController.java
  src/main/java/com/trinity/ctc/domain/fcm/repository/FcmRepository.java
  src/main/java/com/trinity/ctc/domain/fcm/service/FcmService.java
  src/main/java/com/trinity/ctc/domain/restaurant/service/RestaurantFileLoader.java
Labels: release
